name: Executar Script de Performance

on:
  #workflow_dispatch:  # Permite execução manual
  push:
  #schedule:
  #  - cron: '0 0 * * 1'  # Executa toda segunda-feira à meia-noite UTC

jobs:
  run-performance:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código no repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configuração do Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Instalar dependências
      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Executar o script
      - name: Executar o script Python
        run: python performance.py

      # 5. Salvar arquivos de saída como artefatos
      - name: Armazenar os resultados
        uses: actions/upload-artifact@v4
        with:
          name: resultados-performance
          path: |
            data/performance.csv
            data/carteira_anterior.csv

      # 6. (Opcional) Commitar mudanças no repositório
      - name: Commitar resultados no repositório
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add data/performance.csv data/carteira_anterior.csv
          git commit -m "Atualizar resultados do script de performance" || echo "Nenhuma mudança para commitar"
          git push
